name: CD

on:
    push:
        branches:
            - prod

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Dokku deploy
              uses: vitalyliber/dokku-github-action@v4.0
              env:
                  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
                  PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
                  HOST: 134.209.222.77
                  PROJECT: drawphone
